name: Thunderstorm-Testing

# Triggers the workflow on pull request events
on:
  pull_request:
    branches:
      - '*'

jobs:
  testing:
    name: Kotlin Lint Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout github branch
        uses: actions/checkout@v2

      # Setting up JDK
      - name: Set up Java JDK
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 1.8

      # Running Ktlint
      - name: Run ktlint
        run: ./gradlew ktlint

      # Checking build
      - name: Run build test
        run: ./gradlew build
